export const VALID_CATEGORIES = new Set([
  // Literature by region
  "American Literature",
  "British Literature",
  "Classical Literature",
  "European Literature",
  "World Literature",
  "Other Literature",
  // Literature by genre
  "Drama",
  "Poetry",
  "Long Fiction",
  "Short Fiction",
  "Misc. Literature",
  "Misc Literature",
  // History
  "American History",
  "Ancient History",
  "British History",
  "European History",
  "World History",
  "Other History",
  "Historiography",
  "Archaeology",
  // Science
  "Biology",
  "Chemistry",
  "Physics",
  "Math",
  "Astronomy",
  "Computer Science",
  "Earth Science",
  "Engineering",
  "Other Science",
  // Arts
  "Painting",
  "Sculpture",
  "Painting and Sculpture",
  "Painting & Sculpture",
  "Music",
  "Classical Music",
  "Other Fine Arts",
  "Other Arts",
  "Architecture",
  "Photography",
  "Film",
  "Jazz",
  "Opera",
  "Dance",
  "Auditory Fine Arts",
  "Visual Fine Arts",
  // RMPSS
  "Religion",
  "Mythology",
  "Philosophy",
  "Social Science",
  "Economics",
  "Psychology",
  "Linguistics",
  "Sociology",
  "Anthropology",
  // RMPSS compound
  "Beliefs",
  // Other
  "Current Events",
  "Geography",
  "Other Academic",
  "Trash",
  "Popular Culture",
  "Pop Culture",
  // Compound / variant categories used across tournaments
  "Math/Computer Science",
  "Ancient/Other History",
  "Modern World",
  "British/Commonwealth Literature",
  "Other Visual Fine Arts",
  "Other Auditory Fine Arts",
  "Other Science (Computer Science)",
  "Other Science (Astronomy)",
]);

export const WEASEL_WORDS = [
  "famous",
  "famously",
  "notably",
  "notable",
  "noted",
  "well-known",
  "well known",
  "best known",
  "best-known",
  "important",
  "significant",
  "influential",
  "legendary",
  "iconic",
  "renowned",
  "celebrated",
  "prominent",
];

export const WORD_REPLACEMENTS: Record<string, string> = {
  "as well as": "and",
  employ: "use",
  execute: "do/carry out",
  following: "after",
  "in order to": "to",
  "located in": "in",
  nation: "country",
  possess: "have",
  sans: "without",
  upon: "on",
  utilize: "use",
  utilizes: "uses",
  utilized: "used",
  utilizing: "using",
  utilization: "use",
};

export const CONTRACTION_RE =
  /\b(can't|won't|shouldn't|couldn't|wouldn't|isn't|aren't|wasn't|weren't|doesn't|don't|didn't|hasn't|haven't|hadn't|I'm|I've|I'll|I'd|he's|she's|it's|we're|we've|we'll|they're|they've|they'll|there's|that's|who's|what's|where's|how's|let's)\b/gi;
